#!/usr/bin/env node
// IndexNow (https://www.indexnow.org): tell Bing, Yandex, Seznam, Naver and
// the other IndexNow engines which worthmyfee.com pages changed. Bing's index
// also feeds DuckDuckGo, Yahoo and ChatGPT search, which is the point.
//
// .github/workflows/deploy.yml runs this after a push to main is live on both
// Cloud Run (the site) and GitHub Pages (the fallback). Dependency-free (Node 22): this repo has no package.json.
//
//   node scripts/indexnow.mjs --changed <base> <head>   # pages whose HTML changed in base..head
//   node scripts/indexnow.mjs --all                     # every sitemap URL (first run, bulk regen)
//   node scripts/indexnow.mjs --all --dry-run           # print the payload, no POST
//
// Which URLs: the changed files mapped to their public URLs, kept only if the
// URL is in sitemap.xml and robots.txt allows it — the sitemap (generated by
// `npm run pages` in the app repo) is the single list of indexable pages.
//
// The key is public by design: IndexNow proves ownership by fetching
// https://worthmyfee.com/<key>.txt, which lives at the repo root.
//
// Each real submit is also recorded as one PostHog `indexnow_submit` event
// (distinct_id `indexnow`, no person profile), with the project key read from
// the snippet in index.html so it is never duplicated here.
//
// Exit 0 on 200/202 (or nothing to submit), 1 on anything else, 2 on bad args.

import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

export const SITE = 'https://worthmyfee.com';
export const INDEXNOW_KEY = 'f0290cd3888f72fc154819a874bea7b5';
export const INDEXNOW_ENDPOINT = 'https://api.indexnow.org/indexnow';
/** IndexNow accepts at most 10,000 URLs per request. */
export const INDEXNOW_MAX_URLS = 10_000;
export const POSTHOG_HOST = 'https://us.i.posthog.com';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const TIMEOUT_MS = 15_000;

export function extractLocs(sitemapXml) {
  const out = [];
  const re = /<loc>\s*([^<]+?)\s*<\/loc>/g;
  let m;
  while ((m = re.exec(sitemapXml))) {
    const loc = m[1].replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&apos;/g, "'");
    if (loc && !out.includes(loc)) out.push(loc);
  }
  return out;
}

/** Disallow: path prefixes under `User-agent: *` (other agents' groups are ignored). */
export function parseRobotsDisallow(robotsTxt) {
  const out = [];
  let inStar = false;
  let sawRuleSinceAgent = false;
  for (const raw of robotsTxt.split(/\r?\n/)) {
    const line = raw.replace(/#.*$/, '').trim();
    const i = line.indexOf(':');
    if (!line || i < 0) continue;
    const field = line.slice(0, i).trim().toLowerCase();
    const value = line.slice(i + 1).trim();
    if (field === 'user-agent') {
      // Consecutive User-agent lines share one group; a rule line ends the header.
      if (sawRuleSinceAgent) inStar = false;
      sawRuleSinceAgent = false;
      if (value === '*') inStar = true;
      continue;
    }
    sawRuleSinceAgent = true;
    if (inStar && field === 'disallow' && value) out.push(value);
  }
  return out;
}

export function isDisallowed(url, rules) {
  let path;
  try {
    const u = new URL(url);
    path = u.pathname + u.search;
  } catch {
    return true; // unparseable → never submit
  }
  return rules.some(rule => rule && path.startsWith(rule));
}

/**
 * A repo path → the public URL GitHub Pages serves it at, or null for files
 * that are not pages. `index.html` → `/`, `cards/x/index.html` → `/cards/x/`,
 * `privacy.html` → `/privacy.html`.
 */
export function fileToUrl(file, site = SITE) {
  const f = file.replace(/^\.?\//, '');
  if (!f.endsWith('.html')) return null;
  if (f === 'index.html') return `${site}/`;
  if (f.endsWith('/index.html')) return `${site}/${f.slice(0, -'index.html'.length)}`;
  return `${site}/${f}`;
}

/**
 * The URLs to submit: `candidates` (null = the whole sitemap) kept only if
 * they are in the sitemap and robots.txt allows them, capped at the limit.
 */
export function selectUrls(candidates, sitemapXml, robotsTxt, max = INDEXNOW_MAX_URLS) {
  const locs = extractLocs(sitemapXml);
  const inSitemap = new Set(locs);
  const rules = parseRobotsDisallow(robotsTxt);
  const pool = candidates === null ? locs : [...new Set(candidates)].filter(u => inSitemap.has(u));
  return pool.filter(u => !isDisallowed(u, rules)).slice(0, max);
}

export function buildPayload(urlList, { site = SITE, key = INDEXNOW_KEY } = {}) {
  return { host: new URL(site).host, key, keyLocation: `${site}/${key}.txt`, urlList };
}

export function verdict(status) {
  switch (status) {
    case 200: case 202: return 'accepted';
    case 400: return 'bad request (malformed payload)';
    case 403: return 'key not valid (key file missing or content mismatch)';
    case 422: return 'URLs do not match the host / key location';
    case 429: return 'too many requests (spam guard) — retry later';
    default: return 'unexpected status';
  }
}

export const isAccepted = status => status === 200 || status === 202;

/** The PostHog project key from the snippet in index.html (`posthog.init('phc_…'`). */
export function posthogKeyFrom(html) {
  const m = /posthog\.init\(\s*['"](phc_[A-Za-z0-9]+)['"]/.exec(html);
  return m ? m[1] : null;
}

export function posthogEvent(apiKey, properties) {
  return {
    api_key: apiKey,
    event: 'indexnow_submit',
    distinct_id: 'indexnow',
    properties: { ...properties, $process_person_profile: false },
  };
}

function changedFiles(base, head) {
  // --no-renames: a moved page counts as a new path (submitted if in the sitemap).
  const out = execFileSync('git', ['diff', '--name-only', '--no-renames', '--diff-filter=ACMR', base, head], { cwd: ROOT, encoding: 'utf8' });
  return out.split('\n').map(s => s.trim()).filter(Boolean);
}

async function main(argv) {
  const dryRun = argv.includes('--dry-run');
  const all = argv.includes('--all');
  const ci = argv.indexOf('--changed');
  if (all === (ci >= 0)) {
    console.error('usage: indexnow.mjs (--all | --changed <base> <head>) [--dry-run]');
    return 2;
  }
  let candidates = null;
  if (ci >= 0) {
    const [base, head] = [argv[ci + 1], argv[ci + 2]];
    if (!base || !head || base.startsWith('--') || head.startsWith('--')) {
      console.error('--changed wants two revisions: --changed <base> <head>');
      return 2;
    }
    const files = changedFiles(base, head);
    candidates = files.map(f => fileToUrl(f)).filter(Boolean);
    console.log(`${base.slice(0, 7)}..${head.slice(0, 7)}: ${files.length} files changed, ${candidates.length} pages`);
  }

  const read = f => readFileSync(join(ROOT, f), 'utf8');
  const urlList = selectUrls(candidates, read('sitemap.xml'), read('robots.txt'));
  if (urlList.length === 0) {
    console.log('nothing to submit (no changed page is in the sitemap)');
    return 0;
  }
  const payload = buildPayload(urlList);
  console.log(`${urlList.length} URLs to submit (cap ${INDEXNOW_MAX_URLS})`);
  if (dryRun) {
    console.log(JSON.stringify({ ...payload, urlList: urlList.slice(0, 20) }, null, 2));
    if (urlList.length > 20) console.log(`… ${urlList.length - 20} more URLs`);
    console.log('--dry-run: not POSTing');
    return 0;
  }

  const res = await fetch(INDEXNOW_ENDPOINT, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
    body: JSON.stringify(payload),
    signal: AbortSignal.timeout(TIMEOUT_MS),
  });
  const body = (await res.text()).trim();
  const v = verdict(res.status);
  console.log(`POST ${INDEXNOW_ENDPOINT} → HTTP ${res.status}: ${v}${body ? ` (${body.slice(0, 200)})` : ''}`);

  // Best effort: a PostHog outage never fails the submit.
  const phKey = posthogKeyFrom(read('index.html'));
  if (phKey) {
    try {
      const ph = await fetch(`${POSTHOG_HOST}/i/v0/e/`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(posthogEvent(phKey, { mode: all ? 'all' : 'changed', submitted: urlList.length, status: res.status, verdict: v })),
        signal: AbortSignal.timeout(TIMEOUT_MS),
      });
      if (!ph.ok) console.error(`posthog: HTTP ${ph.status} (ignored)`);
    } catch (e) {
      console.error(`posthog: ${e?.message || e} (ignored)`);
    }
  } else {
    console.error('posthog: no project key found in index.html, event not recorded');
  }
  return isAccepted(res.status) ? 0 : 1;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  main(process.argv.slice(2)).then(code => process.exit(code), e => {
    console.error(`indexnow failed: ${e?.message || e}`);
    process.exit(1);
  });
}
